# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk_version: [ '19' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk_version }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
